openapi: 3.1.0
info:
  title: Product
  description: Product
  version: 1.0.0
servers:
  - url: 'https://localhost:8000'
paths:
  /products:
    get:
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/QParam'
      responses:
        '200':
          description: Product list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multipleProducts:
                  value:
                    - name: "Pomme"
                      expiration_datetime: "2025-09-01T10:00:00Z"
                      price: 1000
                    - name: "Banane"
                      expiration_datetime: "2025-09-10T15:30:00Z"
                      price: 2000
                emptyList:
                  value: []

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
      required:
        - name
        - expiration_datetime
        - price

  parameters:
    LimitParam:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        example: 10

    QParam:
      name: q
      in: query
      required: false
      schema:
        type: string
        example: "fruit"
  
